import { useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { format, subMonths } from "date-fns";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Download } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import { DateRangeFilter } from "../components/DateRangeFilter";
import { DailyInsightsChart } from "../components/DailyInsightsChart";
import { KpiCards } from "../components/KpiCards";

export function DashboardPage(){const today=format(new Date(),"yyyy-MM-dd");const defaultFrom=format(subMonths(new Date(),1),"yyyy-MM-dd");const [params,setParams]=useSearchParams();const pageId=params.get("page_id")||"";const from=params.get("from")||defaultFrom;const to=params.get("to")||today;const {data:pages=[]}=useQuery({queryKey:["pages"],queryFn:api.pages});useEffect(()=>{if(!pageId&&pages[0])setParams({page_id:String(pages[0].id),from,to},{replace:true})},[pageId,pages,from,to,setParams]);const {data:report,isLoading}=useQuery({queryKey:["report",pageId,from,to],queryFn:()=>api.report(Number(pageId),from,to),enabled:Boolean(pageId)});return <section><header className="dashboard-header"><div><p className="eyebrow">FACEBOOK REPORTING</p><h1>Tổng quan Facebook</h1><p className="muted">Báo cáo hiệu quả nội dung theo Page và thời gian.</p></div>{report&&<a className="download" href={`/api/reports/${pageId}/excel?from=${from}&to=${to}`}><Download/> Tải Excel</a>}</header><DateRangeFilter pages={pages} pageId={pageId} from={from} to={to} onChange={v=>setParams({page_id:v.pageId,from:v.from,to:v.to})}/>{isLoading&&<div className="notice">Đang tải báo cáo…</div>}{report&&<><p className="freshness">Đồng bộ gần nhất: {report.latest_sync_at?new Date(report.latest_sync_at).toLocaleString("vi-VN"):"Chưa có dữ liệu"}</p><KpiCards summary={report.summary}/><div className="dashboard-grid"><article className="panel"><h2>Số bài đăng theo ngày</h2><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.daily_posts}><CartesianGrid stroke="#263852" vertical={false}/><XAxis dataKey="metric_date" stroke="#7890ae"/><YAxis stroke="#7890ae"/><Tooltip/><Bar dataKey="posts" fill="#3b82f6" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></article><article className="panel"><h2>Top 5 bài tương tác cao</h2><ol className="top-posts">{report.top_posts.map(post=><li key={post.external_post_id}><a href={post.permalink||"#"} target="_blank" rel="noreferrer">{post.message||"Bài không có nội dung"}</a><strong>{new Intl.NumberFormat("vi-VN").format(post.engagement)}</strong></li>)}</ol></article></div><DailyInsightsChart data={report.daily_insights}/></>}</section>}
